import { Suspense } from "react";
import type { Metadata } from "next";
import { ClerkProvider, SignedIn, UserButton } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "@/providers/ReactQueryProvider";
import { SyncUser } from "@/components/SyncUser";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hangman Game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ReactQueryProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <Suspense fallback={<div>Loading...</div>}>
              <SignedIn>
                <header className="flex justify-end items-center p-4 gap-4 h-16">
                  <UserButton />
                </header>
                <SyncUser />
              </SignedIn>
              {children}
            </Suspense>
          </body>
        </html>
      </ReactQueryProvider>
    </ClerkProvider>
  );
}
